DROP TABLE IF EXISTS artiste CASCADE;
DROP TABLE IF EXISTS groupe CASCADE;
DROP TABLE IF EXISTS morceau CASCADE;
DROP TABLE IF EXISTS album CASCADE;
DROP TABLE IF EXISTS utilisateur CASCADE;
DROP TABLE IF EXISTS playlist CASCADE;

DROP TABLE IF EXISTS suivreU CASCADE;
DROP TABLE IF EXISTS suivreG CASCADE;
DROP TABLE IF EXISTS contient CASCADE;
DROP TABLE IF EXISTS compose CASCADE;
DROP TABLE IF EXISTS participe CASCADE;
DROP TABLE IF EXISTS appartient CASCADE;

