DROP TABLE IF EXISTS magasin CASCADE;
DROP TABLE IF EXISTS client CASCADE;
DROP TABLE IF EXISTS produit CASCADE;
DROP TABLE IF EXISTS stocke CASCADE;
DROP TABLE IF EXISTS contient CASCADE;
DROP TABLE IF EXISTS facture CASCADE;
